{% set version = '1.5-8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-magic
  version: {{ version|replace("-", "_") }}

source:
  fn: magic_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/magic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/magic/magic_{{ version }}.tar.gz
  sha256: 7f8bc26e05003168e9d2dadf64eb9a34b51bc41beba482208874803dee7d6c20

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-abind
  run:
    - r-base
    - r-abind

test:
  commands:
    - $R -e "library('magic')"           # [not win]
    - "\"%R%\" -e \"library('magic')\""  # [win]

about:
  home: https://github.com/RobinHankin/magic.git
  license: GPL-2
  summary: A collection of efficient, vectorized algorithms for the creation and investigation
    of magic squares and hypercubes, including a variety of functions for the manipulation
    and analysis of arbitrarily dimensioned arrays.  The package includes methods for
    creating normal magic squares of any order greater than 2.  The ultimate intention
    is for the package to be a computerized embodiment all magic square knowledge, including
    direct numerical verification of properties of magic squares (such as recent results
    on the determinant of odd-ordered semimagic squares).  Some antimagic functionality
    is included.  The package also serves as a rebuttal to the often-heard comment "I
    thought R was just for statistics".
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
