travis:
  secure:
    BINSTAR_TOKEN: q+f4CDDFUAX5BLIZ2UQUFJ6YVkZANdVFFSQ9d6fBfgWbyGJTorCC0Hk/lUkRmXUOXYfh6RJSS77Q1iBMNKLbkqAPxzvkwg/aQq9Exoi0T2qDSczSssmFkkFx1VqDoqUiMcLHlLqx+6SlCt5HneNmzburMgiFSmIsKtQxvZLSfGCperIShhfLOi+exdVREid9X7u85jRXSLEwqSsBBRPPWrq1HU+UTnQdDlw1NBvqKKFxKISb5l++E8b1KfGJMzqkBnOXc4g9MpSiLY+c3poROgdWjvu0yli+nz4eynHLHHdA1WmoedlE4piQV02JZ/F8hjzQ2xcRkvg2YDCR+lKg4fl+DS+OEsRowhyYANsiQFzuc9+AU/yF8icYdsHSGNZwgVcbd1vsKMG3Kb2rB14bXG7k4rGrpm6OGKJQ528T7j0CNTLOtzO7eBS4z3BD2veR2U7qtB4sTBumCaiEhDbqV9NQJVSazr7NlKwMscdX2aJtewC9DBw92u7d1TfHpFGnykv6hxEIjmeGtNMpkTq24cgMraPA/3gXcLBjE2gQI1DfWA76Khzxc6BSQJZiBF9hertKIVxPYolKvORn/lOLGKNIKqjq+fmWKspmO+/Pl/Qb5xX5kP5rARTmKqY52ef76G7w4fi3jpwN6jHOs/BPS70p3G1fA1ABt+zDnPvdsSM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
