travis:
  secure:
    BINSTAR_TOKEN: Gr4l7DXq1W1hhjjFl+6C9cauWn1v6Ab4KG8xn+HYl25JDH/igKBYgm1CTLqT6gA6HIz7CdT9Z+D8Q5AvzMR2kSmnFkprXAKL5dlulLsOdVvnIno4pMc3AofDU+GMW26XXGARSqRlnw4RysU2pSDLagsdKOZIK/afAw2C6EQ+iFTIwDMaxmhDQk2cSCvTU3ey4kkOTGiSbnqz7JhKT/ZcKyAi4bhqaTFJZ7Z1FtY9njKl6cV6MbiULISFKjOP84GrJSzgvhzS2ddeHSRc0ZRyT0Rq19ZHGY25lCXihiQ1mfNSGvxLCU1p5dU8lG/9tqh8By/Uk9FSalwwYUgLObHVC0kEqQkCpqc4Nte4Mi/WvngIFnMiKCgFF+6byQN/ERPZaQxlRUHKrQCCOXcLB5pNDa24sQdBa0Ic5SXVDoi6sTtJkII3B2/LrJOlm1r0LV8qQzTZMof9WMMeNufb3c/S8MjGJV7JcpulptTSuySB3IAMeHcxIdNlJjw/xd76rp9kSABbOJGw9ZqMlWhj1jpU8wi+OCVGTDy8Fn63x+s/caJpPJ/lIcA5wGOY+Jnw5BhQ8YQSstwWQCr5OEiCgy+WMH6gnKNcWDmqQ94hd9xpMIGlCo7VAJsu4yqmRoVLVjQyuIsn7kSqfh6Yod3Cjm8ItH6l6j13Kf8IpIkn7J9FINU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
